-- CAMXD Store: isolated Web Push subscription table.
-- This file is intentionally NOT executed automatically.
create table if not exists public.admin_push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  subscription jsonb not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.admin_push_subscriptions enable row level security;

drop policy if exists "admin push insert own" on public.admin_push_subscriptions;
create policy "admin push insert own"
on public.admin_push_subscriptions
for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists "admin push update own" on public.admin_push_subscriptions;
create policy "admin push update own"
on public.admin_push_subscriptions
for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "admin push select own" on public.admin_push_subscriptions;
create policy "admin push select own"
on public.admin_push_subscriptions
for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "admin push delete own" on public.admin_push_subscriptions;
create policy "admin push delete own"
on public.admin_push_subscriptions
for delete to authenticated
using (auth.uid() = user_id);

create index if not exists admin_push_subscriptions_user_id_idx
  on public.admin_push_subscriptions(user_id);
